defaults: &defaults
  :cs_api:
    :challenges: 'http://cs-api-sandbox.herokuapp.com/v1/challenges'
    :members: 'http://cs-api-sandbox.herokuapp.com/v1/members'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults